packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@prisma/engines": false
  esbuild: true
  msgpackr-extract: true
  prisma: false
  workerd: true
onlyBuiltDependencies:
  - "@prisma/engines"
  - "prisma"
  - "@prisma/client"
